import logging
import re
import os
import io
from flask import Flask, request, render_template, flash, redirect
from werkzeug.utils import secure_filename
from docx import Document
import mammoth
from tabulate import tabulate

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = './uploads'
app.config['ALLOWED_EXTENSIONS'] = {'docx'}

if not os.path.exists(app.config['UPLOAD_FOLDER']):
    os.makedirs(app.config['UPLOAD_FOLDER'])

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']

def word_table_to_markdown(filename):
    doc = Document(filename)
    markdown_tables = []

    for table in doc.tables:
        data = []

        for row in table.rows:
            cell_data = []

            for cell in row.cells:
                cell_data.append(cell.text)

            data.append(cell_data)

        markdown_tables.append(tabulate(data, tablefmt="pipe", headers="firstrow"))

    return "\n".join(markdown_tables)

def replace_images_with_placeholder(content, images):
    img_regex = r'!\[.*?\]\((.*?)\)'
    placeholder = '[ADD IMAGE HERE]'
    result = re.sub(img_regex, lambda match: placeholder if match.group(1) in images else match.group(0), content)

    # Remove characters and whitespace between "(data:image" and ")"
    result = re.sub(r'\(data:image.*?\)', '', result)

    return result

def replace_urls(content):
    # Change URLs starting with "https://learn.microsoft.com/azure/" to "/azure/..."
    result = re.sub(r'https://learn.microsoft.com/azure/(.+)', r'/azure/\1', content)
    return result

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename).replace("\\", "/")
            file.save(filepath)

            # Convert DOCX to Markdown
            with open(filepath, "rb") as docx_file:
                result = mammoth.convert_to_markdown(docx_file).value

            # Extract tables from word doc and convert to markdown
            tables_md = word_table_to_markdown(filepath)

            # Combine markdown text and tables
            result = result + "\n\n" + tables_md

            # Remove trailing whitespaces from each line
            result = '\n'.join(line.rstrip() for line in result.split('\n'))

            # Remove escape character from markdown
            result = result.replace("\\.", ".").replace("\\)", ")").replace("\\-", "-").replace("\\(", "(").replace("\\]", "]").replace("\\[", "[").replace("\\#", "#")

            # Remove "https://learn.microsoft.com/en-us" from links and keep the remaining URL intact
            result = re.sub(r'https://learn.microsoft.com/[a-z]+-[a-z]+(/azure)?', '/azure', result)
            
            # Replace URLs in the Markdown content
            result = replace_urls(result)
            
            # Remove double spaces and replace them with a single space
            result = result.replace('  ', ' ')

            # Replace double underscore with double asterisks
            result = re.sub(r'__(.*?)__', r'**\1**', result)
            
            # Replace double underscore with double asterisks for bold phrases
            result = re.sub(r' \*\*(.*?)', r'** \1', result)

            # Replace "-** " with "- **"
            result = re.sub(r'-\*\*\s(.+)', r'- **\1', result)
        
            # Remove periods with space on both sides
            # result = result.replace('. ', '')

            # Get the list of image URLs in the markdown
            images = re.findall(r'!\[.*?\]\((.*?)\)', result)

            # Replace images with placeholder (excluding autogenerated images)
            result = replace_images_with_placeholder(result, images)

            os.remove(filepath)
            return render_template('index.html', markdown_content=result)

    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)
